on: push
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - run: "docker run --rm ghcr.io/montlhery/noirtier 'BANDERA: 252641DE42D56AB5' > output.mp3"
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: output.mp3
